### ISSUE TITLE
Lmbench.py test case fails

### ISSUE THREAD

**Issue by rakshithprakash** [avocado-framework-tests/avocado-misc-tests#888] opened 2018-05-15 07:12 UTC
Hi,
I'm trying to run the lmbench testcase in my local machine with the following command : 
avocado run /home/rakshith/PerfCI/avocado-misc-tests/perf/lmbench.py --show-job-log 

and I see that the test case is hitting the following errors : 

2018-05-11 11:21:42,717 process          L0591 INFO | Running 'make rerun'
2018-05-11 11:21:42,721 process          L0422 DEBUG| [stdout] cd src && make rerun
2018-05-11 11:21:42,725 process          L0422 DEBUG| [stdout] make[1]: Entering directory '/var/lib/libvirt/images/avocado_ZWWhy6/avocado_job_zCOu2p/1-_home_rakshith_PerfCI_avocado-misc-tests_perf_lmbench.py_Lmbench.test/src/lmbench3/src'
2018-05-11 11:21:43,245 process          L0422 DEBUG| [stdout] make[2]: Entering directory '/var/lib/libvirt/images/avocado_ZWWhy6/avocado_job_zCOu2p/1-_home_rakshith_PerfCI_avocado-misc-tests_perf_lmbench.py_Lmbench.test/src/lmbench3/src'
2018-05-11 11:21:43,246 process          L0422 DEBUG| [stdout] make[2]: Nothing to be done for 'all'.
2018-05-11 11:21:43,246 process          L0422 DEBUG| [stdout] make[2]: Leaving directory '/var/lib/libvirt/images/avocado_ZWWhy6/avocado_job_zCOu2p/1-_home_rakshith_PerfCI_avocado-misc-tests_perf_lmbench.py_Lmbench.test/src/lmbench3/src'
2018-05-11 11:21:43,762 process          L0422 DEBUG| [stdout] make[2]: Entering directory '/var/lib/libvirt/images/avocado_ZWWhy6/avocado_job_zCOu2p/1-_home_rakshith_PerfCI_avocado-misc-tests_perf_lmbench.py_Lmbench.test/src/lmbench3/src'
2018-05-11 11:21:43,763 process          L0422 DEBUG| [stdout] make[2]: Nothing to be done for 'opt'.
2018-05-11 11:21:43,764 process          L0422 DEBUG| [stdout] make[2]: Leaving directory '/var/lib/libvirt/images/avocado_ZWWhy6/avocado_job_zCOu2p/1-_home_rakshith_PerfCI_avocado-misc-tests_perf_lmbench.py_Lmbench.test/src/lmbench3/src'
2018-05-12 11:19:09,065 stacktrace       L0041 ERROR|
2018-05-12 11:19:09,065 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/core/test.py:864
2018-05-12 11:19:09,067 stacktrace       L0047 ERROR| Traceback (most recent call last):
2018-05-12 11:19:09,067 stacktrace       L0047 ERROR|   File "/home/rakshith/PerfCI/avocado-misc-tests/perf/lmbench.py", line 108, in test
2018-05-12 11:19:09,067 stacktrace       L0047 ERROR|     build.make(self.sourcedir, extra_args='rerun')
2018-05-12 11:19:09,068 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/build.py", line 88, in make
2018-05-12 11:19:09,068 stacktrace       L0047 ERROR|     result = run_make(path, make, extra_args, kwargs)
2018-05-12 11:19:09,069 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/build.py", line 54, in run_make
2018-05-12 11:19:09,069 stacktrace       L0047 ERROR|     make_process = process.run(cmd, **process_kwargs)
2018-05-12 11:19:09,070 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/process.py", line 1307, in run
2018-05-12 11:19:09,070 stacktrace       L0047 ERROR|     cmd_result = sp.run(timeout=timeout)
2018-05-12 11:19:09,070 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/process.py", line 815, in run
2018-05-12 11:19:09,070 stacktrace       L0047 ERROR|     self.wait()
2018-05-12 11:19:09,071 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/utils/process.py", line 767, in wait
2018-05-12 11:19:09,071 stacktrace       L0047 ERROR|     rc = self._popen.wait()
2018-05-12 11:19:09,071 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
2018-05-12 11:19:09,071 stacktrace       L0047 ERROR|     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
2018-05-12 11:19:09,072 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
2018-05-12 11:19:09,072 stacktrace       L0047 ERROR|     return func(*args)
2018-05-12 11:19:09,072 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/core/runner.py", line 310, in sigterm_handler
2018-05-12 11:19:09,072 stacktrace       L0047 ERROR|     raise RuntimeError("Test interrupted by SIGTERM")
2018-05-12 11:19:09,072 stacktrace       L0047 ERROR| RuntimeError: Test interrupted by SIGTERM
2018-05-12 11:19:09,073 stacktrace       L0048 ERROR|
2018-05-12 11:19:09,073 test             L0869 DEBUG| Local variables:
2018-05-12 11:19:09,139 test             L0872 DEBUG|  -> self <class 'lmbench.Lmbench'>: 1-/home/rakshith/PerfCI/avocado-misc-tests/perf/lmbench.py:Lmbench.test
2018-05-12 11:19:09,140 test             L0289 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2018-05-12 11:19:09,144 test             L0289 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2018-05-12 11:19:09,144 test             L0289 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2018-05-12 11:19:09,145 test             L1019 ERROR| Traceback (most recent call last):

2018-05-12 11:19:09,146 test             L1019 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-60.0-py2.7.egg/avocado/core/test.py", line 955, in _run_avocado
    raise test_exception

2018-05-12 11:19:09,147 test             L1019 ERROR| RuntimeError: Test interrupted by SIGTERM

2018-05-12 11:19:09,147 test             L1034 ERROR| ERROR 1-/home/rakshith/PerfCI/avocado-misc-tests/perf/lmbench.py:Lmbench.test -> RuntimeError: Test interrupted by SIGTERM

Also attaching the job results data. 
[lmbenchlogs.tar.gz](https://github.com/avocado-framework-tests/avocado-misc-tests/files/2003784/lmbenchlogs.tar.gz)

**Comment by nasastry** [comment] 2018-06-12 05:16
@rakshithprakash On what machine you have ran the above ... I am running on a PowerVM LPAR with RHEL7.5 and not seeing any errors.

```
...
Running 'make rerun'
[stdout] cd src && make rerun
[stdout] make[1]: Entering directory `/var/tmp/avocado_8QZtTA/avocado_job_wRTLRB/1-lmbench.py_Lmbench.test/lmbench3/src'
[stdout] gmake[2]: Entering directory `/var/tmp/avocado_8QZtTA/avocado_job_wRTLRB/1-lmbench.py_Lmbench.test/lmbench3/src'
[stdout] gmake[2]: Nothing to be done for `all'.
[stdout] gmake[2]: Leaving directory `/var/tmp/avocado_8QZtTA/avocado_job_wRTLRB/1-lmbench.py_Lmbench.test/lmbench3/src'
[stdout] gmake[2]: Entering directory `/var/tmp/avocado_8QZtTA/avocado_job_wRTLRB/1-lmbench.py_Lmbench.test/lmbench3/src'
[stdout] gmake[2]: Nothing to be done for `opt'.
[stdout] gmake[2]: Leaving directory `/var/tmp/avocado_8QZtTA/avocado_job_wRTLRB/1-lmbench.py_Lmbench.test/lmbench3/src'
Using config in CONFIG.ltczep2-lp4.aus.stglabs.ibm.com
Tue Jun 12 10:40:39 IST 2018
Latency measurements
Tue Jun 12 10:41:31 IST 2018
Calculating file system latency
Tue Jun 12 10:41:33 IST 2018
Local networking
Tue Jun 12 10:44:10 IST 2018
Bandwidth measurements
...
```
Test is running.

**Comment by nasastry** [comment] 2018-06-12 14:07
@rakshithprakash Please let me know if the issue is still re-producible in your environment. If so please share your environment details else we can close this issue. Thanks!!

**Comment by PraveenPenguin** [comment] 2018-06-21 03:37
@nasastry yes for me also it not reproducible at all but @rakshithprakash requested memory param also in lmbench test and i think you already added this  so i think we can close this issue , @rakshithprakash can you please confirm

**Comment by rakshithprakash** [comment] 2018-06-21 06:42
@PraveenPenguin I did test the code which @nasastry  provided me with the MB parameter added and I don't see this issue now. But we have another issue where we cannot see the results being collected in the results directory. How do we track it? Can we go ahead with it in the same bug or do you want me to open another bug to track it? 
We discussed to add "make see" at the end of the run to generate the results.

**Comment by PraveenPenguin** [comment] 2018-06-25 05:28
@rakshithprakash i think we can close this issue and go with new issue , it help to track issues and make good progress ,

**Closed** 2018-07-05 05:46 UTC
