### ISSUE TITLE
Run of Compilebench.test on embedded linux device leads to crash of Avocado

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#690] opened 2017-11-09 10:01 UTC
If the test `Compilebench.test` (located in `~/avocado-misc-tests-master/perf/compilebench.py`) is executed when running the performance tests with `avocado run ~/avocado-misc-tests-master/perf` (I use [avocado v55.0 from PyPi](https://pypi.python.org/pypi/avocado-framework/55.0)) it throws a RuntimeError. The following tests in the test suite are executed.

```
$ avocado run ~/avocado-misc-tests-master/perf
JOB ID     : b03ec98d21a4f007645642e2abc04275c0627e0d
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-08T15.38-b03ec98/job.log
 ...
 (03/16) /home/rc/avocado-misc-tests-master/perf/compilebench.py:Compilebench.test: -
Avocado crashed: RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/job.py", line 474, in run_tests
    execution_order)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 616, in run_suite
    deadline):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 396, in run_test
    proc.start()

  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)

  File "/usr/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()

  File "/usr/lib/python2.7/multiprocessing/process.py", line 274, in _bootstrap
    sys.stderr.write('Process %s:\n' % self.name)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 640, in write
    self._log_line("%s\n" % data_lines[0])

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 651, in _log_line
    logger.log(self._level, prefix + line)

  File "/usr/lib/python2.7/logging/__init__.py", line 1216, in log
    self._log(level, msg, args, **kwargs)

  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)

  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)

  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)

  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)

  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)

  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)

  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)

  File "/usr/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')

  File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)

... (traceback between line 474, in run_tests and line 13, in _print repeated many times)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 640, in write
    self._log_line("%s\n" % data_lines[0])

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 651, in _log_line
    logger.log(self._level, prefix + line)

  File "/usr/lib/python2.7/logging/__init__.py", line 1216, in log
    self._log(level, msg, args, **kwargs)

  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)

  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)

  File "/usr/lib/python2.7/logging/__init__.py", line 271, in __init__
    self.module = os.path.splitext(self.filename)[0]

  File "/usr/lib/python2.7/posixpath.py", line 105, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)

  File "/usr/lib/python2.7/genericpath.py", line 101, in _splitext
    if p[filenameIndex] != extsep:

RuntimeError: maximum recursion depth exceeded in cmp

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
Error running method "render" of plugin "xunit": [Errno 28] No space left on device
ERROR (770.18 s)
 (04/16) /home/rc/avocado-misc-tests-master/perf/hackbench.py:Hackbench.test:
```

[Initial Issue report in the avocado repo](https://github.com/avocado-framework/avocado/issues/2286).

**Comment by PraveenPenguin** [comment] 2017-11-21 06:17
@fkromer for me test always passed as i think you are facing this issue as you have limited resource in your setup machine and i don't have access of these kind of setup  so not able to reproduce it in my environment , may be this test need to skip on these kind of setup , can you please help more about your setup or it is really helpful if you able to send fix , looking forward for your response

**Comment by fkromer** [comment] 2017-11-22 08:02
@PraveenPenguin Is the `ulimit -a` info from https://github.com/avocado-framework-tests/avocado-misc-tests/issues/697#issuecomment-346271733 giving you the info you need?

**Comment by PraveenPenguin** [comment] 2017-11-27 08:57
@fkromer setting my set up with your ulimit still i am not able to reproduce this issue

**Comment by fkromer** [comment] 2017-11-27 09:11
@PraveenPenguin I will run this test again with another embedded linux board as well https://github.com/avocado-framework-tests/avocado-misc-tests/issues/697#issuecomment-346830158.

**Comment by PraveenPenguin** [comment] 2017-11-28 06:05
@fkromer sure thanks  , please let us know   the results

**Comment by PraveenPenguin** [comment] 2018-05-09 08:52
@fkromer any update on this if you still facing this please let us know

**Comment by fkromer** [comment] 2018-05-09 09:02
@PraveenPenguin This had no sufficient priority for me until now to justify that I spend time on it. If you want to close the issue just close it. I can reopen it if if required later...

**Comment by PraveenPenguin** [comment] 2018-05-09 09:15
@fkromer sure closing now

**Closed by PraveenPenguin** 2018-05-09 09:15 UTC
