### ISSUE TITLE
IO driver test suite test 3 execution leads to an "OSError: [Errno 8] Exec format error"

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#691] opened 2017-11-09 11:06 UTC
If I run the IO driver test suite with `avocado run ~/avocado-misc-tests-master/io/driver` (I downloaded and unzipped the test repository into `~/avocado-misc-tests-master`) the execution of test 3 leads to an error:

    2017-11-09 10:46:57,002 test             L0965 ERROR| ERROR 3-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt -> OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt)

Seems like the test runner tries to execute `/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt` which is indicated to be a test but actually isn't:

```
avocado list ~/avocado-misc-tests-master/io/driver
INSTRUMENTED /home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py:DriverBindTest.test
SIMPLE       /home/rc/avocado-misc-tests-master/io/driver/module_unload_load.sh
SIMPLE       /home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt
SIMPLE       /home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml
```

The relevant log file content: 

```
2017-11-09 10:46:55,777 test             L0381 INFO | START 3-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt
2017-11-09 10:46:55,795 test             L0402 DEBUG| Test metadata:
2017-11-09 10:46:55,813 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt
2017-11-09 10:46:55,908 process          L0389 INFO | Running '/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt'
2017-11-09 10:46:56,045 stacktrace       L0041 ERROR| 
2017-11-09 10:46:56,049 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-11-09 10:46:56,081 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-11-09 10:46:56,087 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 1113, in test
2017-11-09 10:46:56,089 stacktrace       L0047 ERROR|     self._execute_cmd()
2017-11-09 10:46:56,092 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 1097, in _execute_cmd
2017-11-09 10:46:56,094 stacktrace       L0047 ERROR|     env=test_params)
2017-11-09 10:46:56,112 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1114, in run
2017-11-09 10:46:56,115 stacktrace       L0047 ERROR|     cmd_result = sp.run(timeout=timeout)
2017-11-09 10:46:56,127 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 638, in run
2017-11-09 10:46:56,130 stacktrace       L0047 ERROR|     self._init_subprocess()
2017-11-09 10:46:56,132 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 402, in _init_subprocess
2017-11-09 10:46:56,135 stacktrace       L0047 ERROR|     raise details
2017-11-09 10:46:56,137 stacktrace       L0047 ERROR| OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt)
2017-11-09 10:46:56,149 stacktrace       L0048 ERROR| 
2017-11-09 10:46:56,152 test             L0822 DEBUG| Local variables:
2017-11-09 10:46:56,959 test             L0825 DEBUG|  -> self <class 'avocado.core.test.SimpleTest'>: 3-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt
2017-11-09 10:46:56,965 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
2017-11-09 10:46:56,982 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
2017-11-09 10:46:56,986 test             L0950 ERROR| Traceback (most recent call last):

2017-11-09 10:46:56,988 test             L0950 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 888, in _run_avocado
    raise test_exception

2017-11-09 10:46:56,990 test             L0950 ERROR| OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt)

2017-11-09 10:46:57,002 test             L0965 ERROR| ERROR 3-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt -> OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/README.txt)
2017-11-09 10:46:57,004 test             L0954 INFO | 
2017-11-09 10:46:57,208 sysinfo          L0415 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2017-11-09 10:46:57,231 sysinfo          L0426 INFO | Files configured by file: /etc/avocado/sysinfo/files
2017-11-09 10:46:57,237 sysinfo          L0446 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2017-11-09 10:46:57,239 sysinfo          L0454 INFO | Profiler disabled
2017-11-09 10:46:57,461 sysinfo          L0266 DEBUG| Journalctl collection failed: [Errno 2] No such file or directory (journalctl --quiet --lines 1 --output json)
2017-11-09 10:46:57,474 varianter        L0116 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2017-11-09 10:46:57,487 test             L0381 INFO | START 4-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml
```

**Comment by narasimhan-v** [comment] 2017-11-29 04:52
@fkromer This is an issue because of the execute permission given to those files which are actually not a test. Working on it.

Thanks for the report.

**Comment by narasimhan-v** [comment] 2017-11-29 05:09
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/711 should fix it

**Comment by fkromer** [comment] 2017-11-29 08:44
@narasimhan-v I still 2 errors due to `avocado-misc-tests-1/io/driver/driver_bind_test.py.data/README.txt` and `avocado-misc-tests-1/io/driver/driver_bind_test.py.data/driver_bind_test.yaml`:

```
$ avocado run avocado-misc-tests-1/io/driver/
JOB ID     : f9069af238bc3488da67c40a2245c4821cd6b8cb
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-29T08.38-f9069af/job.log
 (1/4) avocado-misc-tests-1/io/driver/driver_bind_test.py:DriverBindTest.test: CANCEL (0.01 s)
 (2/4) avocado-misc-tests-1/io/driver/module_unload_load.sh: PASS (0.83 s)
 (3/4) avocado-misc-tests-1/io/driver/driver_bind_test.py.data/README.txt: ERROR (0.05 s)
 (4/4) avocado-misc-tests-1/io/driver/driver_bind_test.py.data/driver_bind_test.yaml: ERROR (0.05 s)
RESULTS    : PASS 1 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 1.57 s

```

**Comment by narasimhan-v** [comment] 2017-11-29 10:25
@fkromer Have you applied the patch from #711 ?

**Comment by fkromer** [comment] 2017-11-29 11:49
@narasimhan-v Oh, I missed the patch. Works just fine...

```
$ avocado run avocado-misc-tests-1/io/driver/
JOB ID     : 6560a4ccc04281582b36a12bd113c68daf2806b4
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-29T10.53-6560a4c/job.log
 (1/1) avocado-misc-tests-1/io/driver/driver_bind_test.py:DriverBindTest.test: CANCEL (0.02 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 0.52 s
```

**Comment by PraveenPenguin** [comment] 2017-11-30 04:31
@fkromer can we close this issue if it works for you

**Comment by narasimhan-v** [comment] 2017-11-30 05:57
Since @fkromer has confirmed and the PR has merged, closing this.

**Closed by narasimhan-v** 2017-11-30 05:57 UTC
