### ISSUE TITLE
can't fetch livepatch

### ISSUE THREAD

**Issue by kyle-ibm** [avocado-framework-tests/avocado-misc-tests#1375] opened 2019-10-24 08:26 UTC
Fetching livepatch from github fails even though the file does seem like it's available

2019-10-05 07:32:03,222 livepatch L0091 INFO | ============== Building livepatching Module =================
2019-10-05 07:32:03,223 download L0070 INFO | Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c -> /root/tests/data/cache/by_location/e0a3fb95cbb9946a3a809841f5755f86bb9bb828/livepatch-sample.c.f0yFlH
2019-10-05 07:32:08,478 asset L0194 ERROR| OSError: [Errno 2] No such file or directory: '/root/tests/data/cache/by_location/e0a3fb95cbb9946a3a809841f5755f86bb9bb828/livepatch-sample.c.f0yFlH'
2019-10-05 07:32:08,478 stacktrace L0041 ERROR|
2019-10-05 07:32:08,478 stacktrace L0044 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
2019-10-05 07:32:08,480 stacktrace L0047 ERROR| Traceback (most recent call last):
2019-10-05 07:32:08,480 stacktrace L0047 ERROR| File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 167, in test
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| self.build_module()
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 97, in build_module
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| self.livepatch_file = self.fetch_asset(self.location, expire='7d')
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 1078, in fetch_asset
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| self.cache_dirs, expire).fetch()
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/utils/asset.py", line 196, in fetch
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| raise EnvironmentError("Failed to fetch %s." % basename)
2019-10-05 07:32:08,481 stacktrace L0047 ERROR| EnvironmentError: Failed to fetch livepatch-sample.c.
2019-10-05 07:32:08,482 stacktrace L0048 ERROR|

**Comment by kyle-ibm** [comment] 2019-10-24 09:01
same for fetch issue for kprobe and kretprobe tests also

**Comment by PraveenPenguin** [comment] 2019-11-04 05:30
@kyle-ibm in my env it always works 
```stdout] kernel-headers-4.18.0-147.el8.ppc64le
Command 'rpm -q kernel-headers' finished with 0 after 0.0389978885651s
============== Building kretprobe Module =================
Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c -> /home/OpTest/avocado-fvt-wrapper-py2/data/cache/by_location/48c1a66fa7a1adf63028164388977b906c59d418/kretprobe_example.c.sk3T8T
Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c": content-length 2998, date: "Mon, 04 Nov 2019 05:29:00 GMT", last-modified: "UNKNOWN"
Running 'make'
```
may be system has n/w issue can  you please  do manual wget

**Comment by alfredyswu** [comment] 2019-11-05 04:18
Hi PraveenPenguin , 
I could access the URL via web explorer
But in Mihawk wget command response ERROR 403: Forbidden.


[root@mihawk-sut1-nvmeg4 kernel]# wget https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
--2019-11-05 12:12:05--  https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by '/ST=CA/L=CU/O=TREND/OU=IWSS/CN=IWSS.TREND':
  Self-signed certificate encountered.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
[root@mihawk-sut1-nvmeg4 kernel]#
[root@mihawk-sut1-nvmeg4 kernel]#
[root@mihawk-sut1-nvmeg4 kernel]# wget  --no-check-certificate  https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
--2019-11-05 12:12:19--  https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
WARNING: cannot verify raw.githubusercontent.com's certificate, issued by '/ST=CA/L=CU/O=TREND/OU=IWSS/CN=IWSS.TREND':
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 403 Forbidden
2019-11-05 12:12:24 ERROR 403: Forbidden.

[root@mihawk-sut1-nvmeg4 kernel]#



> @kyle-ibm in my env it always works
> 
> ```
> Command 'rpm -q kernel-headers' finished with 0 after 0.0389978885651s
> ============== Building kretprobe Module =================
> Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c -> /home/OpTest/avocado-fvt-wrapper-py2/data/cache/by_location/48c1a66fa7a1adf63028164388977b906c59d418/kretprobe_example.c.sk3T8T
> Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c": content-length 2998, date: "Mon, 04 Nov 2019 05:29:00 GMT", last-modified: "UNKNOWN"
> Running 'make'
> ```
> 
> may be system has n/w issue can you please do manual wget and verify is as it able to fetch file

**Comment by PraveenPenguin** [comment] 2019-11-05 04:53
@nasastry can you please help here, as  i think it is system ssl issue

**Comment by alfredyswu** [comment] 2019-11-12 10:05
We have seen the same issue in below test. FYI
  kernel/livepatch.py
  RAS/kprobe.py
  RAS/kretprobe.py
  fs/fs-fuzz.py
  fs/fsx.py
  fs/pjdfstest.py

**Comment by alfredyswu** [comment] 2019-11-29 04:03
kprobe culd pass after put the file on internal http server and edit URL in python script.

PASS 1-kprobe.py:Kprobe.test

**Comment by alfredyswu** [comment] 2019-11-29 04:39
These "can't fetch " issue should caused by wistron network firewall which block some URLs.
It doesn't relate to the script.

**Comment by PraveenPenguin** [comment] 2019-11-29 04:44
@narasimhan-v one thought can we have those script in py.data directory i know is not good or we can have yaml entry having file location configurabale

**Comment by narasimhan-v** [comment] 2019-11-29 07:31
@PraveenPenguin One thing that I can suggest is:  Get the URL via yaml.
So that the URL can be public or private, and can be controlled via yaml instead of changing script.
Setting a private http server can be done by the user.

**Comment by PraveenPenguin** [comment] 2019-11-29 08:08
@narasimhan-v looks good so we can go with yaml solution

**Closed** 2023-02-22 13:56 UTC
